export const exploreData = [
  {
    img: "/PJM020719Q202_Luxe_WanakaNZ_LivingRoom_0264-LightOn_R1.jpg",
    location: "London",
    distance: "45-minute drive",
  },
  {
    img: "/Airbnb 43715467 2.jpg",
    location: "Manchester",
    distance: "4.5-hour drive",
  },
  {
    img: "/theBoot.jpg",
    location: "Liverpool",
    distance: "4.5-hour drive",
  },
  {
    img: "/top-airbnb-alternatives-2021-1613057911.jpg",
    location: "New York",
    distance: "4-hour drive",
  },
  {
    img: "/airbnb_3d4e6ad9-2971-4b6a-90aa-3a4cfcce9f7e.jpg",
    location: "Cardiff",
    distance: "45-minute drive",
  },
  {
    img: "/airbnb-hero-.jpg",
    location: "Birkenhead",
    distance: "4.5-hour drive",
  },
  {
    img: "/Airbnb.jpg",
    location: "Newquay",
    distance: "6-hour drive",
  },
  {
    img: "/airbnb-melbourne-australia.jpg",
    location: "Hove",
    distance: "2-hour drive",
  },
];

export const cardsDate = [
  { img: "/mod.jpeg", title: "Outdoor getaways" },
  { img: "/airbnb3.jpg", title: "Unique stays" },
  { img: "/Airbnb.jpg", title: "Entire homes" },
  { img: "/airbnb-hero-.jpg", title: "Exclusive" },
  {
    img: "/airbnb-melbourne-australia.jpg",
    title: "Top Stays",
  },
  {
    img: "/PJM020719Q202_Luxe_WanakaNZ_LivingRoom_0264-LightOn_R1.jpg",
    title: "Just for you",
  },
];

export const searchDate = [
  {
    img: "/PJM020719Q202_Luxe_WanakaNZ_LivingRoom_0264-LightOn_R1.jpg",
    long: "",
    lat: "",
    location: "Manchester",
    title: "Independent luxury Studio",
    desc: "Here at airbnb we bring your home to you. So just eat, sleep, relax and get some rest",
    price: "$37/night",
    id: 1,
    star: 4.3,
    total: "$117 total",
  },
  {
    img: "/Airbnb 43715467 2.jpg",
    long: "",
    lat: "",
    location: "Manchester",
    title: "Stay at a spacoius environment",
    desc: "Here at airbnb we bring your home to you. So just eat, sleep, relax and get some rest",
    price: "$24/night",
    id: 2,
    star: 4.6,
    total: "$120 total",
  },
  {
    img: "/theBoot.jpg",
    long: "",
    lat: "",
    location: "Liverpool",
    title: "Independent luxury Studio",
    desc: "Here at airbnb we bring your home to you. So just eat, sleep, relax and get some rest",
    price: "$38/night",
    id: 3,
    star: 4.2,
    total: "$138 total",
  },
  {
    img: "/top-airbnb-alternatives-2021-1613057911.jpg",
    long: "",
    lat: "",
    location: "New York",
    title: "Stay with you in mind",
    desc: "Here at airbnb we bring your home to you. So just eat, sleep, relax and get some rest",
    price: "$20/night",
    id: 4,
    star: 4.6,
    total: "$127 total",
  },
  {
    img: "/airbnb_3d4e6ad9-2971-4b6a-90aa-3a4cfcce9f7e.jpg",
    long: "",
    lat: "",
    location: "Cardiff",
    title: "Flexing you is all we want",
    desc: "Here at airbnb we bring your home to you. So just eat, sleep, relax and get some rest",
    price: "$34/night",
    id: 5,
    star: 4.7,
    total: "$140 total",
  },
  {
    img: "/airbnb-hero-.jpg",
    long: "",
    lat: "",
    location: "Birkenhead",
    title: "All about client satisfaction",
    desc: "Here at airbnb we bring your home to you. So just eat, sleep, relax and get some rest",
    price: "$15/night",
    id: 6,
    star: 4.5,
    total: "$137 total",
  },
  {
    img: "/Airbnb.jpg",
    long: "",
    lat: "",
    location: "Newquay",
    title: "Totally made for you",
    desc: "Here at airbnb we bring your home to you. So just eat, sleep, relax and get some rest",
    price: "$54/night",
    id: 7,
    star: 4.8,
    total: "$217 total",
  },
  {
    img: "/airbnb-melbourne-australia.jpg",
    long: "",
    lat: "",
    location: "Canada",
    title: "Residence prepared for your family",
    desc: "Here at airbnb we bring your home to you. So just eat, sleep, relax and get some rest",
    price: "$45/night",
    id: 8,
    star: 4.5,
    total: "$207 total",
  },
];
